version: '3'
services:
  jira-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - ${DB_FILES_LOCATION}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    labels:
      - traefik.enable=false
    networks:
      - internal

  jira-web:
    image: atlassian/jira-software:${JIRA_VERSION}
    restart: unless-stopped
    volumes:
      -  ${JIRA_FILES_LOCATION}:/var/atlassian/application-data/jira
    expose:
      - 8080
    labels:
      - traefik.docker.network=${EXTERNAL_NETWORK}
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.port=8080
    environment:
      - ATL_PROXY_NAME=${DOMAIN}
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    networks:
      - internal
      - traefik
    depends_on:
      - jira-db

networks:
  traefik:
    external:
      name: ${EXTERNAL_NETWORK}
  internal:
    driver: bridge
